# Generated by Django 3.0.3 on 2020-03-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default=None)),
                ('day', models.IntegerField(default=None)),
                ('time', models.TimeField(auto_now_add=True)),
                ('hometask', models.TextField(default='')),
                ('is_done', models.BooleanField(default=False)),
            ],
        ),
    ]
