# Generated by Django 3.0.3 on 2020-03-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='lesson',
            name='user',
            field=models.TextField(default='admin'),
            preserve_default=False,
        ),
    ]
